/****************************************************************************
 * This is free and unencumbered software released into the public domain.
 *
 * Anyone is free to copy, modify, publish, use, compile, sell, or
 * distribute this software, either in source code form or as a compiled
 * binary, for any purpose, commercial or non-commercial, and by any
 * means.
 *
 * In jurisdictions that recognize copyright laws, the author or authors
 * of this software dedicate any and all copyright interest in the
 * software to the public domain. We make this dedication for the benefit
 * of the public at large and to the detriment of our heirs and
 * successors. We intend this dedication to be an overt act of
 * relinquishment in perpetuity of all present and future rights to this
 * software under copyright law.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
 * OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 * For more information, please refer to <https://unlicense.org>
 ***************************************************************************/
/*---------------------------------------------------------------------------
    Lib SLI v1.00

    Author  : White Guy That Don't Smile
    Date    : 2021/11/27, Saturday, November 27th; 1140 HOURS
    License : UnLicense | Public Domain

    This is a C library for processing Nintendo's SLI data.
    It is compliant with the "MIO0", "CMPR"/"SMSR00", "Yay0",
    and "Yaz0" formats generated by Nintendo for the Nintendo 64.
    Second and third party developers may have made alterations
    to the SLI algorithm which aren't replicated by this software.
---------------------------------------------------------------------------*/



#ifndef LIBSLI_H_INCLUDED
#define LIBSLI_H_INCLUDED



#define ENCODE 0
#define DECODE 1
#define MIO  0x4D494F30
#define CMPR 0x434D5052
#define SMSR 0x534D5352
#define Yay  0x59617930
#define Yaz  0x59617A30



/*------------------------------------------------------
At the expense of RAM, adjusting this macro value
will improve execution time during encoding by reducing
the frequency of re-allocation calls with the work
buffer(s) in use, in addition to, increasing the
possibility of errors concerning integer overflows or
allocation rejection.
The aforementioned macro corresponds to the number of
bits that will be left-shifted by a hard-coded value
as part of an incremental supplement in conjunction
with work RAM buffers used for storing encoded data
representation elements.
[Safe]
  0 =   4096 (Standard)
  1 =   8192
[Risky]
  2 =  16384
  3 =  32768
[Asking for Trouble]
  4 =  65536
  5 = 131072
[Absolute Madman]
  6 = 262144
  7 = 524288
------------------------------------------------------*/
#define ENC_GREED 2



typedef   signed char  i8;
typedef unsigned char  u8;
typedef   signed short i16;
typedef unsigned short u16;
#ifdef __x86_64__
typedef   signed int   i32;
typedef unsigned int   u32;
#else
typedef   signed long  i32;
typedef unsigned long  u32;
#endif



enum { MIO0 = 1, SMSR00, Yay0, Yaz0 };



u16 _swap16( u16 data );
u32 _swap32( u32 data );
void process_sli( u8 *src, u8 **dst,
                  const u32 srclen, u32 *dstlen,
                  const u32 type, const u32 mode );
void _search( u8 *src, u32 mypos, const u32 data_size,
              i32 *match_position, u32 *match_length,
              const u32 max_length );
u8 *_encode_mio0( u8 *src, u8 **dst,
                  const u32 srclen, u32 *dstlen );
u8 *_encode_smsr00( u8 *src, u8 **dst,
                    const u32 srclen, u32 *dstlen );
u8 *_encode_yay0( u8 *src, u8 **dst,
                  const u32 srclen, u32 *dstlen );
u8 *_encode_yaz0( u8 *src, u8 **dst,
                  const u32 srclen, u32 *dstlen );
u8 *_decode_mio0( u8 *src, u8 **dst );
u8 *_decode_smsr00( u8 *src, u8 **dst );
u8 *_decode_yay0( u8 *src, u8 **dst );
u8 *_decode_yaz0( u8 *src, u8 **dst );



#endif
