/****************************************************************************
 * This is free and unencumbered software released into the public domain.
 *
 * Anyone is free to copy, modify, publish, use, compile, sell, or
 * distribute this software, either in source code form or as a compiled
 * binary, for any purpose, commercial or non-commercial, and by any
 * means.
 *
 * In jurisdictions that recognize copyright laws, the author or authors
 * of this software dedicate any and all copyright interest in the
 * software to the public domain. We make this dedication for the benefit
 * of the public at large and to the detriment of our heirs and
 * successors. We intend this dedication to be an overt act of
 * relinquishment in perpetuity of all present and future rights to this
 * software under copyright law.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
 * OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 * For more information, please refer to <https://unlicense.org>
 ***************************************************************************/
/*---------------------------------------------------------------------------
    Lib SLI v1.00

    Author  : White Guy That Don't Smile
    Date    : 2021/11/27, Saturday, November 27th; 1140 HOURS
    License : UnLicense | Public Domain

    This is a C library for processing Nintendo's SLI data.
    It is compliant with the "MIO0", "CMPR"/"SMSR00", "Yay0",
    and "Yaz0" formats generated by Nintendo for the Nintendo 64.
    Second and third party developers may have made alterations
    to the SLI algorithm which aren't replicated by this software.
---------------------------------------------------------------------------*/



#include "libsli.h"
#include <stdio.h>



static const char *_s_magic[] = { "MIO0", "SMSR00", "Yay0", "Yaz0" };



void process_sli( u8 *src, u8 **dst,
                  const u32 srclen, u32 *dstlen,
                  const u32 type, const u32 mode )
{
  u8 *retval = (u8 *)0;

  switch ( type )
  {
    case MIO0:
      retval = ( mode == ENCODE )
               ? _encode_mio0( src, &*dst, srclen, &*dstlen )
               : _decode_mio0( src, &*dst );
      break;
    case SMSR00:
      retval = ( mode == ENCODE )
               ? _encode_smsr00( src, &*dst, srclen, &*dstlen )
               : _decode_smsr00( src, &*dst );
      break;
    case Yay0:
      retval = ( mode == ENCODE )
               ? _encode_yay0( src, &*dst, srclen, &*dstlen )
               : _decode_yay0( src, &*dst );
      break;
    case Yaz0:
      retval = ( mode == ENCODE )
               ? _encode_yaz0( src, &*dst, srclen, &*dstlen )
               : _decode_yaz0( src, &*dst );
      break;
    default:
      printf( "Unrecognized Type: %u\n", (unsigned)type );
      break;
  }

  if ( retval == (u8 *)0 )
  {
    if ( (type >= 1) && (type <= 4) )
    {
      printf( "Unsuccessful %s process!\n", _s_magic[type - 1] );
    }
  }

  return;
}
